language: go
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
install:
  - go get github.com/GildasCh/fcomp
  - go get gopkg.in/h2non/filetype.v1
  - go get github.com/stretchr/testify/assert
  - go get github.com/gorilla/mux
